name: PHP Code Quality

on:
  pull_request:
  push:

jobs:
  test:

    runs-on: ${{ matrix.operating-system }}

    strategy:
      matrix:
        php-version:
          - "8.3"
          - "8.4"
        operating-system:
          - "ubuntu-latest"

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v4"

      - name: "Install PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          php-version: "${{ matrix.php-version }}"
          ini-values: memory_limit=-1,extension=swow
          tools: composer:v2, cs2pr
          extensions: ds

      - name: "update apt"
        run: "sudo apt update && sudo apt --yes install libcurl4-openssl-dev libssl-dev"

      - name: "install dev packages"
        run: "sudo apt --yes install libcurl4-openssl-dev libssl-dev"

      - name: "Validate composer.json and composer.lock"
        run: composer validate --strict

      - name: "Install dependencies"
        run: composer install --prefer-dist --no-progress --ignore-platform-req=ext-swow

      - name: "Install swow"
        run: "sudo vendor/bin/swow-builder --install"

      - name: "Check coding standards"
        if: ${{ matrix.php-version != '8.4' }}
        run: composer run-script cs:dry-run

      - name: "Check PHPStan"
        run: composer run-script analyse

      - name: "Run test suite"
        run: composer run-script test:unit:coverage
        env:
          XDEBUG_MODE: coverage

      - name: "Validate test coverage"
        uses: "5monkeys/cobertura-action@v14"
        if: github.event_name == 'pull_request' && github.actor != 'dependabot[bot]'
        with:
          path: coverage/coverage.xml
          minimum_coverage: 80
          skip_covered: true
          fail_below_threshold: 80
          only_changed_files: true
          show_class_names: true
          show_missing: true
