name: PHP Code Quality

on:
  pull_request:
  push:

jobs:
  test:

    runs-on: ${{ matrix.operating-system }}

    strategy:
      matrix:
        php-version:
          - "8.3"
        operating-system:
          - "ubuntu-latest"

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v4"

      - name: "Install PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          coverage: "none"
          php-version: "${{ matrix.php-version }}"
          ini-values: memory_limit=-1
          tools: composer:v2, cs2pr
          extensions: ds

      - name: "install dev packages"
        run: "sudo apt --yes install libcurl4-openssl-dev libssl-dev"

      - name: "Validate composer.json and composer.lock"
        run: composer validate

      - name: "Install dependencies"
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: "Install swow"
        run: "sudo vendor/bin/swow-builder --install"

      - name: "Check coding standards"
        run: "vendor/bin/php-cs-fixer fix -v --dry-run"

      - name: "Run test suite"
        run: composer run-script test:unit-github-action
